import { FordCar } from './types';

export const FORD_CARS: FordCar[] = [
  {
    id: 'fusion',
    name: 'فورد فيوجن',
    nameEn: 'Ford Fusion',
    tagline: 'راحة السيدان الفاخرة والقوة والتحكم الديناميكي المتناهي',
    taglineEn: 'Dynamic premium sedan comfort with executive presence',
    category: 'sedans',
    categoryAr: 'سيدان فاخرة',
    priceStartAr: '٢,٢٥٠,٠٠٠ ج.م',
    priceEstimate: 2250000,
    engine: '2.0L EcoBoost Turbocharged 4-Cylinder',
    engineAr: '٢.٠ لتر إيكوبوست تيربو ٤ سلندر',
    horsepower: 240,
    torque: '٣٤٠ نيوتن-متر',
    acceleration: '٧.٣ ثانية',
    transmission: '6-Speed SelectShift Automatic',
    transmissionAr: 'أتوماتيك ٦ سرعات متطور',
    driveTypeAr: 'دفع أمامي ديناميكي',
    fuelEconomyAr: '٨.٤ لتر / ١٠٠ كم',
    fuelTypeAr: 'بنزين ٩٥ الممتاز',
    seats: 5,
    descriptionAr: 'تجمع فورد فيوجن الفاخرة بين الأناقة المطلقة والرفاهية العالية للشخصيات الإدارية والعائلات الراقية في مصر. تأتي بنظام عزل صوتي نشط فريد، ومقاعد جلدية فاخرة قابلة للتبريد والتدفئة، مع ثبات أسطوري وتجربة قيادة تضاهي السيارات الرياضية الفارهة.',
    featuresAr: [
      'نظام عزل الضوضاء النشط للمقصورة ANC',
      'مقاعد تيتانيوم من الجلد الطبيعي بخاصية التدليك والتهوية',
      'سقف زجاجي كهربائي بانورامي متطور',
      'مساعد النقطة العمياء والفرملة التلقائية النشطة ومساعد الحفاظ على المسار',
      'نظام صوتي Sony مجسم بـ 12 مكبر صوت فائق النقاء'
    ],
    colors: [
      { name: 'أبيض لؤلؤي قطبي', hex: '#F9FAFB', nameEn: 'Platinum White' },
      { name: 'فضي بلاتينيوم', hex: '#D1D5DB', nameEn: 'Silver Platinum' },
      { name: 'أزرق كوزميك عميق', hex: '#1E3A8A', nameEn: 'Deep Blue Metallic' },
      { name: 'أسود ملوكي لامع', hex: '#111827', nameEn: 'Tuxedo Black' }
    ],
    image: "/https://static0.carbuzzimages.com/wordpress/wp-content/uploads/gallery-images/original/473000/600/473668.jpg",
    bannerImage: '/src/assets/images/ford_fusion_egypt_1782162667497.jpg',
    performanceScore: 92,
    utilityScore: 88,        
    techScore: 95
  },
  {
    id: 'focus',
    name: 'فورد فوكاس',
    nameEn: 'Ford Focus',
    tagline: 'الأناقة الألمانية والتحكم المثالي على الطرق المصرية',
    taglineEn: 'German precision & perfect handling for Egyptian roads',
    category: 'sedans',
    categoryAr: 'سيدان وهاتشباك',
    priceStartAr: '١,٣٩٠,٠٠٠ ج.م',
    priceEstimate: 1390000,
    engine: '1.5L EcoBoost 3-Cylinder',
    engineAr: '١.٥ لتر إيكوبوست ٣ سلندر',
    horsepower: 120,
    torque: '151 نيوتن-متر',
    acceleration: '١١.٢ ثانية',
    transmission: '6-Speed Automatic',
    transmissionAr: 'أتوماتيك ٦ سرعات',
    driveTypeAr: 'دفع أمامي',
    fuelEconomyAr: '٥.٥ لتر / ١٠٠ كم',
    fuelTypeAr: 'بنزين ٩٢ / ٩٥',
    seats: 5,
    descriptionAr: 'تعتبر فورد فوكاس من أكثر السيارات مبيعاً في فئتها بمصر، وذلك بفضل ثباتها المذهل على السرعات العالية، وتوجيهها الدقيق للغاية، وحزمة الأمان النشطة التي تمنح القائد ثقة تامة في كل منعطف، مع مقصورة ذكية مجهزة بنظام ترفيه SYNC 3 وشاشة عالية الدقة.',
    featuresAr: [
      'شاشة ترفيه ملونة تعمل باللمس مقاس 8 بوصة',
      'ثبات إلكتروني متقدم ESP مع التحكم في الجر',
      'كاميرا خلفية وحساسات ركن أمامية وخلفية',
      'نظام صوتي فاخر بـ 6 مكبرات صوت',
      'مصابيح أمامية كاملة LED متكيفة'
    ],
    colors: [
      { name: 'أزرق كوزميك', hex: '#1E3A8A', nameEn: 'Cosmic Blue' },
      { name: 'أبيض قطبي', hex: '#F9FAFB', nameEn: 'Polar White' },
      { name: 'رمادي مغناطيسي', hex: '#4B5563', nameEn: 'Magnetic Gray' },
      { name: 'أسود ليلي', hex: '#111827', nameEn: 'Shadow Black' },
      { name: 'أحمر قرمزي', hex: '#991B1B', nameEn: 'Ruby Red' }
    ],
    image: '/src/assets/images/ford_focus_egypt_1782161780739.jpg',
    bannerImage: '/src/assets/images/ford_focus_egypt_1782161780739.jpg',
    performanceScore: 82,
    utilityScore: 85,
    techScore: 88
  },
  {
    id: 'puma',
    name: 'فورد بوما',
    nameEn: 'Ford Puma',
    tagline: 'الكروس أوفر الرياضية المدمجة والذكية للمدينة',
    taglineEn: 'The sporty, compact, and smart crossover for the city',
    category: 'suvs-crossovers',
    categoryAr: 'كروس أوفر / SUV',
    priceStartAr: '١,٤٥٠,٠٠٠ ج.م',
    priceEstimate: 1450000,
    engine: '1.0L EcoBoost Turbo Mild-Hybrid',
    engineAr: '١.٠ لتر إيكوبوست تيربو هجين بسيط',
    horsepower: 125,
    torque: '٢١٠ نيوتن-متر',
    acceleration: '٩.٨ ثانية',
    transmission: '7-Speed Dual-Clutch Automatic',
    transmissionAr: 'أتوماتيك ثنائي التعشيق ٧ سرعات',
    driveTypeAr: 'دفع أمامي',
    fuelEconomyAr: '٤.٩ لتر / ١٠٠ كم (موفرة للغاية)',
    fuelTypeAr: 'بنزين هجين',
    seats: 5,
    descriptionAr: 'فورد بوما هي تحفة فنية مدمجة بتصميم خارجي ديناميكي وهجومي مستوحى من الكوبيه. تتميز بمساحة تخزين خلفية ذكية (MegaBox) قابلة للغسيل ومحرك حائز على جوائز عالمية يوفر أداءً جباراً واستهلاك وقود هو الأفضل في فئتها في شوارع مصر المزدحمة.',
    featuresAr: [
      'صندوق الأمتعة الذكي MegaBox بسعة 80 لتر إضافية ومسبك تصريف',
      'عدادات رقمية بالكامل مقاس 12.3 بوصة قابلة للتخصيص',
      'مساعد القيادة المتكامل Co-Pilot360',
      'سقف بانورامي كهربائي بالكامل',
      'نظام صوتي بريميوم من B&O بـ 10 مكبرات صوت'
    ],
    colors: [
      { name: 'رمادي مطفي', hex: '#78716C', nameEn: 'Desert Grey' },
      { name: 'أحمر ناري', hex: '#DC2626', nameEn: 'Lucid Red' },
      { name: 'أزرق المحيط', hex: '#0284C7', nameEn: 'Ocean Blue' },
      { name: 'أبيض ثلجي', hex: '#FFFFFF', nameEn: 'Frozen White' },
      { name: 'أسود معتم', hex: '#1C1917', nameEn: 'Agate Black' }
    ],
    image: '/src/assets/images/ford_puma_egypt_1782161796424.jpg',
    bannerImage: '/src/assets/images/ford_puma_egypt_1782161796424.jpg',
    performanceScore: 84,
    utilityScore: 82,
    techScore: 92
  },
  {
    id: 'kuga',
    name: 'فورد كوجا / إسكيب',
    nameEn: 'Ford Kuga',
    tagline: 'الـ SUV العائلية الذكية والمثالية للسفر والمغامرة',
    taglineEn: 'The smart family SUV engineered for memorable journeys',
    category: 'suvs-crossovers',
    categoryAr: 'كروس أوفر / SUV',
    priceStartAr: '١,٨٩٠,٠٠٠ ج.م',
    priceEstimate: 1890000,
    engine: '1.5L EcoBoost Turbocharged',
    engineAr: '١.٥ لتر إيكوبوست تيربو',
    horsepower: 180,
    torque: '٢٤٠ نيوتن-متر',
    acceleration: '٨.٩ ثانية',
    transmission: '8-Speed Automatic',
    transmissionAr: 'أتوماتيك ٨ سرعات',
    driveTypeAr: 'دفع أمامي أو كلي ذكي',
    fuelEconomyAr: '٦.٧ لتر / ١٠٠ كم',
    fuelTypeAr: 'بنزين ٩٥',
    seats: 5,
    descriptionAr: 'تجمع فورد كوجا بين الرحابة العائلية الفائقة والقوة الديناميكية. بفضل مقاعد خلفية قابلة للانزلاق لزيادة مساحة الأمتعة وتصميم انسيابي يقلل مقاومة الهواء، توفر فخامة وسلاسة فائقة في السفر والرحلات الطويلة بين المحافظات المصرية.',
    featuresAr: [
      'مقاعد جلدية فاخرة مع تحكم كهربائي وذاكرة',
      'نظام فتح الشنطة الخلفية الذكي بمجرد تمرير القدم',
      'شاشة عرض المعلومات على الزجاج الأمامي HUD',
      'تكييف أوتوماتيكي ثنائي المناطق مع فتحات خلفية',
      'شاحن لاسلكي للهواتف الذكية'
    ],
    colors: [
      { name: 'فضي معدني', hex: '#94A3B8', nameEn: 'Luxe Silver' },
      { name: 'أزرق عميق', hex: '#1E3A8A', nameEn: 'Deep Blue' },
      { name: 'أخضر غامق', hex: '#064E3B', nameEn: 'Green Forest' },
      { name: 'أبيض برونزي', hex: '#F1F5F9', nameEn: 'Platinum White' },
      { name: 'رمادي داكن', hex: '#334155', nameEn: 'Stone Gray' }
    ],
    image: '/src/assets/images/explorer_city_1782161662332.jpg',
    bannerImage: '/src/assets/images/explorer_city_1782161662332.jpg',
    performanceScore: 86,
    utilityScore: 94,
    techScore: 90
  },
  {
    id: 'mustang',
    name: 'فورد موستانج GT',
    nameEn: 'Ford Mustang GT',
    tagline: 'الأسطورة العضلية الأمريكية الأقوى وصوت الطرب اللامتناهي',
    taglineEn: 'The ultimate American muscle icon with an unforgettable roar',
    category: 'sports',
    categoryAr: 'رياضية فائقة',
    priceStartAr: '٤,٩٥٠,٠٠٠ ج.م',
    priceEstimate: 4950000,
    engine: '5.0L Coyote V8 Naturally Aspirated',
    engineAr: '٥.٠ لتر كويوتي V8 تنفس طبيعي',
    horsepower: 486,
    torque: '٥٦٠ نيوتن-متر',
    acceleration: '٤.٣ ثانية',
    transmission: '10-Speed SelectShift Automatic',
    transmissionAr: 'أتوماتيك ١٠ سرعات متطور',
    driveTypeAr: 'دفع خلفي رياضي',
    fuelEconomyAr: '١١.٨ لتر / ١٠٠ كم',
    fuelTypeAr: 'بنزين ٩٥',
    seats: 4,
    descriptionAr: 'لا تحتاج فورد موستانج إلى تعريف. بمحرك V8 الأسطوري سعة 5.0 لتر ونغمة العادم الهجومية النشطة التي تطرب القلوب، فإنها تمنحك إحساساً خالصاً بالحرية المطلقة على طرق السفر السريعة مع نظام تعليق MagneRide ونمط تفحيط مسار الحلبة.',
    featuresAr: [
      'نظام عادم نشط يحمل صمامات للتحكم بصوت السيارة بالكامل',
      'شاشات بانورامية مزدوجة متصلة (١٢.٤ + ١٣.٢ بوصة)',
      'مكابح برمبو Brembo عالية الأداء بـ 6 مكابس',
      'نظام تعليق مغناطيسي تكيفي MagneRide Damping System',
      'تطبيق مدمج لحساب أوقات التسارع وقياسات الحلبة Track Apps'
    ],
    colors: [
      { name: 'أحمر رابيد غامق', hex: '#7F1D1D', nameEn: 'Rapid Red' },
      { name: 'أزرق توربو', hex: '#1D4ED8', nameEn: 'Grabber Blue' },
      { name: 'أصفر نيون', hex: '#EAB308', nameEn: 'Yellow Splash' },
      { name: 'رمادي كربوني', hex: '#1E293B', nameEn: 'Carbonized Gray' },
      { name: 'أسود فخم', hex: '#000000', nameEn: 'Shadow Black' }
    ],
    image: '/src/assets/images/mustang_gt_1782161616041.jpg',
    bannerImage: '/src/assets/images/mustang_gt_1782161616041.jpg',
    performanceScore: 99,
    utilityScore: 50,
    techScore: 96
  },
  {
    id: 'bronco',
    name: 'فورد برونكو باد لاندز',
    nameEn: 'Ford Bronco Badlands',
    tagline: 'وحش الطرق الوعرة المصمم لقهر الصحاري والجبال المصرية',
    taglineEn: 'Built wild to dominate rugged mountains and sand dunes',
    category: 'suvs-crossovers',
    categoryAr: 'سيارة جبلية / برية',
    priceStartAr: '٣,٨٠٠,٠٠٠ ج.م',
    priceEstimate: 3800000,
    engine: '2.7L EcoBoost Twin-Turbo V6',
    engineAr: '٢.٧ لتر إيكوبوست توين تيربو V6',
    horsepower: 330,
    torque: '٥٦٣ نيوتن-متر',
    acceleration: '٦.١ ثانية',
    transmission: '10-Speed Automatic with Trail Control',
    transmissionAr: 'أتوماتيك ١٠ سرعات مع مساعد المسار',
    driveTypeAr: 'دفع رباعي متطور مع أقفال دفرنش',
    fuelEconomyAr: '١٠.٣ لتر / ١٠٠ كم',
    fuelTypeAr: 'بنزين ٩٥',
    seats: 5,
    descriptionAr: 'تمت هندسة فورد برونكو باد لاندز لتكون آلة تخطي الصعاب القصوى. بأبواب وسقف قابلة للفك لمنحك تجربة الهواء الطلق المثيرة في رحلات دهب أو سيناء، ونظام تعليق HOSS المتطور لامتصاص الصدمات في أشد البيئات قسوة وصحراء الواحات.',
    featuresAr: [
      'سقف صلب وأبواب قابلة للفك والتخزين بالكامل بسهولة',
      'نظام القيادة على التضاريس GOAT Modes (٧ وضعيات مختلفة)',
      'تعليق رياضي متطور مخصص للبر HOSS 2.0 Bilstein Dampers',
      'كاميرا محيطية 360 درجة مع خطوط ملاحة برية على الإطارات',
      'أقفال أمامية وخلفية كاملة للتروس الفرقية (Differential Locks)'
    ],
    colors: [
      { name: 'برتقالي سايبر', hex: '#F97316', nameEn: 'Cyber Orange' },
      { name: 'أخضر عشبي بري', hex: '#166534', nameEn: 'Eruption Green' },
      { name: 'أزرق رمادي', hex: '#57534E', nameEn: 'Area 51 Blue' },
      { name: 'أبيض طيني', hex: '#F5F5F4', nameEn: 'Cactus Gray' },
      { name: 'أسود معتم', hex: '#0C0A09', nameEn: 'Shadow Black' }
    ],
    image: '/https://static0.carbuzzimages.com/wordpress/wp-content/uploads/gallery-images/original/473000/600/473668.jpg',
    bannerImage: '/https://static0.carbuzzimages.com/wordpress/wp-content/uploads/gallery-images/original/473000/600/473668.jpg',
    performanceScore: 95,
    utilityScore: 92,
    techScore: 91
  },
  {
    id: 'f150',
    name: 'فورد F-150 رابتور',
    nameEn: 'Ford F-150 Raptor',
    tagline: 'الشاحنة الجبارة بلا منازع وقدرات تتخطى كل الحدود والرمال',
    taglineEn: 'The indomitable high-performance desert short-course truck',
    category: 'trucks',
    categoryAr: 'شاحنات نقل / بيك اب',
    priceStartAr: '٥,٦٠٠,٠٠٠ ج.م',
    priceEstimate: 5600000,
    engine: '3.5L Twin-Turbo EcoBoost V6 High-Output',
    engineAr: '٣.٥ لتر توين تيربو إيكوبوست V6 عالي الأداء',
    horsepower: 450,
    torque: '٦٩١ نيوتن-متر',
    acceleration: '٥.٥ ثانية',
    transmission: '10-Speed Automatic with Paddle Shifters',
    transmissionAr: 'أتوماتيك ١٠ سرعات مع بدالات خلف عجلة القيادة',
    driveTypeAr: 'دفع رباعي مستمر ذكي',
    fuelEconomyAr: '١٣.١ لتر / ١٠٠ كم',
    fuelTypeAr: 'بنزين ٩٥',
    seats: 5,
    descriptionAr: 'رابتور هو قمة التطور في فئة البيك أب على مستوى الكوكب. مجهزة بمساعدات صدمات Fox Live Valve التكيفية وجسم مصنوع من سبائك الألمنيوم العسكرية الفائقة القوة المقاومة للخدش والتآكل لتتحمل القفزات الصحراوية العنيفة والمهام شديدة الصعوبة.',
    featuresAr: [
      'مساعدات Fox 3.1 Live Valve التكيفية الأكثر تطوراً في العالم',
      'إطارات تضاريس قاسية 37 بوصة مخصصة كخيار قياسي',
      'نظام صوتي فاخر للغاية من Bang & Olufsen بـ 18 سماعة',
      'مولد طاقة مدمج Pro Power Onboard لتشغيل الأجهزة الكهربائية في البر',
      'توجيه ونظام قيادة بدواسة واحدة للبر Trail 1-Pedal Drive'
    ],
    colors: [
      { name: 'أزرق رابتور ليزر', hex: '#1E40AF', nameEn: 'Raptor Performance Blue' },
      { name: 'رمادي رصاصي', hex: '#1F2937', nameEn: 'Lead Foot Gray' },
      { name: 'أحمر قودو', hex: '#B91C1C', nameEn: 'Code Orange' },
      { name: 'أبيض دوف', hex: '#E5E7EB', nameEn: 'Oxford White' },
      { name: 'أسود معتم', hex: '#030712', nameEn: 'Agate Black' }
    ],
    image: '/src/assets/images/f150_raptor_1782161633235.jpg',
    bannerImage: '/src/assets/images/f150_raptor_1782161633235.jpg',
    performanceScore: 98,
    utilityScore: 99,
    techScore: 94
  }
];

export const WHEEL_OPTIONS = [
  { name: 'جنوط ألومنيوم رياضية خفيفة مقاس ١٧ بوصة', price: 0 },
  { name: 'جنوط رياضية سوداء داكنة مقاس ١٨ بوصة', price: 45000 },
  { name: 'جنوط خليط كربوني خفيف مقاس ١٩ بوصة من أوتو جميل', price: 95000 },
  { name: 'جنوط مغناطيسية رياضية مقاس ٢٠ بوصة للسباق', price: 160000 }
];

export const PACKAGES = [
  {
    name: 'الباقة البرونزية القياسية (Standard)',
    description: 'تشمل اللمسات القياسية الجميلة، طلاء واقي وجنوط ألومنيوم مع ضمان 5 سنوات أو 100 ألف كم.',
    price: 0
  },
  {
    name: 'باقة الرفاهية الذكية من ياسمين فورد (Luxury Pack)',
    description: 'شاحن لاسلكي متطور للجوال، سقف بانورامي عريض للغاية، طلاء معالج حرارياً ضد الخدوش، ونظام تعليق ناعم ومريح.',
    price: 110000
  },
  {
    name: 'الباقة الرياضية الفائقة (ST-Line/Performance Pack)',
    description: 'عادم رياضي ذو نغمة جبارة، مكابح بريمبو حمراء، جناح خلفي رياضي كربوني، ومقاعد ريكارو رياضية حاضنة من ألياف ألكانتارا.',
    price: 240000
  }
];

export const CONTACT_INFO = {
  phone: '01094002675',
  phoneFormatted: '01094002675',
  whatsappUrl: 'https://wa.me/201094002675',
  address: 'بوابة مصر الجديدة - طريق العروبة، القاهرة، جمهورية مصر العربية',
  dealer: 'ياسين فورد مصر (Yassen Ford Egypt) بالتعاون مع الوكيل المعتمد'
};

import { SparePart } from './types';

export const FORD_SPARE_PARTS: SparePart[] = [
  {
    id: 'part-1',
    name: 'تيل فرامل أمامي أصلي Motorcraft',
    category: 'brakes',
    categoryAr: 'مكابح / فرامل',
    carModel: 'fusion',
    carModelAr: 'فورد فيوجن (2015 - 2022)',
    condition: 'new',
    conditionAr: 'جديدة بالتغليف الأصلي',
    price: 3400,
    priceAr: '٣,٤٠٠ ج.م',
    descriptionAr: 'طقم تيل فرامل أمامي أصلي موتركرافت وكالة متوافق بالكامل مع موديلات فورد فيوجن بمختلف الفئات. عمر افتراضي طويل وثبات تام على درجات الحرارة المرتفعة لمكابح مثالية.',
    sellerName: 'موزع معتمد ياسين فورد',
    sellerPhone: '01094002675',
    image: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=600&q=80',
    isVerified: true
  },
  {
    id: 'part-2',
    name: 'طقم بوجيهات ليزر إيريديوم NGK الأصلية',
    category: 'engine',
    categoryAr: 'محرك وأجزاؤه',
    carModel: 'fusion',
    carModelAr: 'فورد فيوجن / فوكاس تيربو',
    condition: 'new',
    conditionAr: 'جديدة',
    price: 1850,
    priceAr: '١,٨٥٠ ج.م',
    descriptionAr: 'طقم بوجيهات 4 قطع إيريديوم ليزر مستوردة، تعطي اشتعالاً ممتازاً للمحرك الإيكوبوست وتقليل استهلاك الوقود المفرط وتحسين التسارع الكلي.',
    sellerName: 'هاني قطع غيار فورد',
    sellerPhone: '01224859341',
    image: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&w=600&q=80',
    isVerified: false
  },
  {
    id: 'part-3',
    name: 'فلتر هواء تيربو ذكي أصلي فورد',
    category: 'filters',
    categoryAr: 'فلاتر وزيوت',
    carModel: 'focus',
    carModelAr: 'فورد فوكاس (2018 - 2024)',
    condition: 'new',
    conditionAr: 'جديدة',
    price: 950,
    priceAr: '٩٥٠ ج.م',
    descriptionAr: 'فلتر هواء أصلي من التوكيل للوقاية القصوى لمحرك سيارتك من الأتربة الدقيقة على الطرق الصحراوية لجمهورية مصر العربية. يحافظ على العزم.',
    sellerName: 'ياسين فورد ستور',
    sellerPhone: '01094002675',
    image: 'https://images.unsplash.com/photo-1552656967-7a0991a13906?auto=format&fit=crop&w=600&q=80',
    isVerified: true
  },
  {
    id: 'part-4',
    name: 'مساعدين غاز بلستين ألمانيا للبر الصعب',
    category: 'suspension',
    categoryAr: 'عفشة ومساعدين',
    carModel: 'bronco',
    carModelAr: 'فورد برونكو / إيدج',
    condition: 'used',
    conditionAr: 'مستعملة بحالة ممتازة كالجديدة',
    price: 16500,
    priceAr: '١٦,٥٠٠ ج.م',
    descriptionAr: 'طقم مساعدين غاز خلفي ماركة Bilstein الألمانية الشهيرة للمغامرين وراكبي البر، بحالة ممتازة كسر زيرو خالية تماماً من العيوب لتوفير ثبات لامتناهي.',
    sellerName: 'المهندس كريم التونسي',
    sellerPhone: '01150493821',
    image: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=600&q=80',
    isVerified: false
  },
  {
    id: 'part-5',
    name: 'غطاء مراية كربون فايبر هجومي رياضي',
    category: 'accessories',
    categoryAr: 'إكسسوارات وكماليات',
    carModel: 'mustang',
    carModelAr: 'فورد موستانج GT',
    condition: 'new',
    conditionAr: 'جديدة',
    price: 2900,
    priceAr: '٢,٩٠٠ ج.م',
    descriptionAr: 'زوج أغطية حماية كربون فايبر حقيقي للمرايا مع تصميم قرن الثور الهجومي المستوحى من حلبات السباق والـ ST. لصق دبل فيس 3M متين للغاية.',
    sellerName: 'تامر أوتو ستايلنج الدقي',
    sellerPhone: '01012948632',
    image: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=600&q=80',
    isVerified: false
  }
];

